apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshots
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            dev.okteto.com/inject-token: "true"
        spec:
          containers:
          - name: snapshots
            image: okteto.dev/runner:0.0.1
            command: ["/bin/sh", "-c"]
            args:
              - kubectl get all;
                echo waiting;
                sleep 10;
                echo after sleep;
                ls -al;
          restartPolicy: Never
