apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshots
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: snapshots
            image: okteto/okteto:2.24.1
            command: ["/bin/sh", "-c"]
            args:
              - kubectl get all;
                echo waiting;
                sleep 10;
                echo after sleep;
                kubectl get pods;
          restartPolicy: Never
