apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshots
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            dev.okteto.com/inject-token: "true"
        spec:
          containers:
          - name: snapshots
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - sleep 60;
          restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: ten-minute-job
spec:
  template:
    spec:
      containers:
      - name: ten-minute-job
        image: busybox
        command: ["/bin/sh", "-c", "
          echo 'Job started';
          sleep 600;
          echo 'Job completed';
        "]
      restartPolicy: Never
  backoffLimit: 4
